package com.bank.bian.cardterminaladministration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Card Terminal Administration
 *
 * Business Area:      Sales and Service
 * Business Domain:    Channels
 * Functional Pattern: Administer
 * Asset Type:         Card Terminal
 * Control Record:     Card Terminal Administrative Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Card Terminal Administration — BIAN Semantic API")
                .description("Service Domain 'Card Terminal Administration' (Administer pattern) "
                        + "operating on the 'Card Terminal Administrative Plan' control record.")
                .version("0.1.0"));
    }
}
